FROM tomcat:9-jdk8
LABEL author="Ramesh"
LABEL organization="Quality Thought"
COPY gameoflife.war /usr/local/tomcat/webapps/gameoflife.war
EXPOSE 8080
# If The tomcat starts my application will starts, so i'm ok with the
# CMD of the base image
