# Never try to use latest version over here
FROM httpd:alpine3.15
# Provide the source and Destination of the file
COPY "index.html" "/usr/local/apache2/htdocs/index.html"
# Our container/application will require 80 port
EXPOSE 80