---
 - name: Ansible Blocks
   hosts: all
   gather_facts: false

   tasks:
     - block:
        - name: Install apache httpd
          apt:
            name: apache2
            state: present
          tags: apache
        - name: enable and start the service
          ansible.builtin.service:
            name: apache2
            state: started
          become: yes
        - name: Print the message
          debug:
            msg: "This for block section"
        - name: copy the content remote server
          ansible.builtin.template:
            src: /home/ansible/testing/mine.j2
            dest: /etc/mydest