---
- name: install apache
  hosts: webservers
  become: yes
  tasks:
  - name: install apache
    package:
      name: apache2
      state: present
    notify:
    - enable and restart apache  
  handlers:
  - name: enable and restart apache
    service:
      name: apache2
      enabled: 
      state: restarted