---
- name: install httpd pacakage
  hosts: all
  # become: yes
  tasks:
    - block:
        - name: Install apache httpd
          apt:
            name: apache2
            state: present
          tags: apache
        - name: copy the content from source to destination
          ansible.builtin.copy:
            src: /home/ansible/testing/mine.j2
            dest: /etc/mydest
        - name: Print the message of apache installation
          debug:
            msg: "Successfully installation completed and browse for apache page"
          tags: msg
          notify:
          - Restart apache2
        - name: enable and start the service
          ansible.builtin.service:
            name: apache2
            state: started
            #  become: yes
            #tags: apachestarted
  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted
        become: yes
        tags: apachestarted
      ignore_errors: yes